# Generated by Django 5.0.2 on 2024-02-20 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ManageAPI', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='path',
        ),
        migrations.AddField(
            model_name='image',
            name='unique_name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='evidence_images',
            field=models.ManyToManyField(blank=True, null=True, related_name='evidence_images', to='ManageAPI.image'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='invoice_images',
            field=models.ManyToManyField(blank=True, null=True, related_name='invoice_images', to='ManageAPI.image'),
        ),
        migrations.DeleteModel(
            name='InvoiceImage',
        ),
    ]
