# Generated by Django 5.0.2 on 2024-02-20 22:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ManageAPI', '0002_remove_image_path_image_unique_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invoice',
            old_name='evidence_images',
            new_name='evi_images',
        ),
        migrations.RenameField(
            model_name='invoice',
            old_name='invoice_images',
            new_name='inv_images',
        ),
    ]
