# Generated by Django 5.0.2 on 2024-02-27 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ManageAPI', '0003_rename_evidence_images_invoice_evi_images_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='state',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
